// Achievements — gamified milestones for streaks, lesson counts, themes explored, etc.

export const ACHIEVEMENTS = [
  {
    code: 'first_step',
    title: 'First Step',
    description: 'Complete your first lesson.',
    icon: '🌱',
    xp_reward: 10,
    condition_type: 'first_lesson',
    condition_value: 1,
    order: 1,
  },
  {
    code: 'quote_curious',
    title: 'Quote Curious',
    description: 'Read 10 stoic quotes.',
    icon: '📜',
    xp_reward: 10,
    condition_type: 'quote_read',
    condition_value: 10,
    order: 2,
  },
  {
    code: 'week_warrior',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak.',
    icon: '🔥',
    xp_reward: 50,
    condition_type: 'streak',
    condition_value: 7,
    order: 3,
  },
  {
    code: 'scholar',
    title: 'Scholar',
    description: 'Complete 10 lessons.',
    icon: '📚',
    xp_reward: 50,
    condition_type: 'lessons_completed',
    condition_value: 10,
    order: 4,
  },
  {
    code: 'explorer',
    title: 'Explorer',
    description: 'Explore 3 different themes.',
    icon: '🧭',
    xp_reward: 25,
    condition_type: 'themes_explored',
    condition_value: 3,
    order: 5,
  },
  {
    code: 'month_master',
    title: 'Month Master',
    description: 'Maintain a 30-day streak.',
    icon: '🏛️',
    xp_reward: 200,
    condition_type: 'streak',
    condition_value: 30,
    order: 6,
  },
  {
    code: 'sage',
    title: 'Sage',
    description: 'Complete 25 lessons.',
    icon: '🦉',
    xp_reward: 150,
    condition_type: 'lessons_completed',
    condition_value: 25,
    order: 7,
  },
  {
    code: 'philosopher',
    title: 'Philosopher',
    description: 'Explore all 8 themes.',
    icon: '🏛️',
    xp_reward: 100,
    condition_type: 'themes_explored',
    condition_value: 8,
    order: 8,
  },
  {
    code: 'collector',
    title: 'Collector',
    description: 'Save 5 favorite quotes or lessons.',
    icon: '⭐',
    xp_reward: 30,
    condition_type: 'favorites',
    condition_value: 5,
    order: 9,
  },
  {
    code: 'stoic_scholar',
    title: 'Stoic Scholar',
    description: 'Complete 50 lessons.',
    icon: '🏆',
    xp_reward: 500,
    condition_type: 'lessons_completed',
    condition_value: 50,
    order: 10,
  },
  {
    code: 'century',
    title: 'Century',
    description: 'Maintain a 100-day streak.',
    icon: '💯',
    xp_reward: 1000,
    condition_type: 'streak',
    condition_value: 100,
    order: 11,
  },
  {
    code: 'devoted',
    title: 'Devoted',
    description: 'Maintain a 365-day streak. A full year of practice.',
    icon: '👑',
    xp_reward: 5000,
    condition_type: 'streak',
    condition_value: 365,
    order: 12,
  },
];
