// Subscription plans — static catalog. Lives in PB.
// `features` is a JSON array of feature codes that this plan unlocks.

export const PLANS = [
  {
    code: 'free',
    name: 'Free',
    tagline: 'Start the practice.',
    description: 'A daily lesson, a quote, and a streak. The basics, forever.',
    price_cents: 0,
    currency: 'USD',
    interval: 'free',
    features: [
      'read_daily_lesson',
      'quote_of_the_day',
      'streak_tracking',
      'basic_themes',
    ],
    highlight: false,
    order: 1,
    active: true,
  },
  {
    code: 'pro_monthly',
    name: 'Pro Monthly',
    tagline: 'Everything, every month.',
    description: 'Full library, all quotes, favorites, offline reading, daily reminders.',
    price_cents: 599,
    currency: 'USD',
    interval: 'monthly',
    features: [
      'unlimited_lessons',
      'unlimited_quotes',
      'favorites_sync',
      'offline_reading',
      'daily_reminders',
      'premium_themes',
      'premium_quotes',
      'premium_lessons',
      'priority_support',
    ],
    highlight: false,
    order: 2,
    active: true,
  },
  {
    code: 'pro_yearly',
    name: 'Pro Yearly',
    tagline: 'Save 30%. A year of practice.',
    description: 'Everything in Pro Monthly, billed yearly. The best value for a committed practice.',
    price_cents: 4999,
    currency: 'USD',
    interval: 'yearly',
    features: [
      'unlimited_lessons',
      'unlimited_quotes',
      'favorites_sync',
      'offline_reading',
      'daily_reminders',
      'premium_themes',
      'premium_quotes',
      'premium_lessons',
      'priority_support',
    ],
    highlight: true,
    order: 3,
    active: true,
  },
  {
    code: 'pro_lifetime',
    name: 'Pro Lifetime',
    tagline: 'Pay once. Practice forever.',
    description: 'Everything, forever, on every device you own. For the truly committed.',
    price_cents: 19900,
    currency: 'USD',
    interval: 'lifetime',
    features: [
      'unlimited_lessons',
      'unlimited_quotes',
      'favorites_sync',
      'offline_reading',
      'daily_reminders',
      'premium_themes',
      'premium_quotes',
      'premium_lessons',
      'priority_support',
      'lifetime_updates',
    ],
    highlight: false,
    order: 4,
    active: true,
  },
];
