// Quick practices — 60-second wisdom cards.
// Each is a hook + a short body + a 1-line action.
// Designed to be read in 60 seconds. The whole set is the "60-second scroll".

export const QUICK_PRACTICES = [
  {
    slug: 'one-thing',
    title: 'The one thing',
    hook: 'One problem, fully faced, beats ten problems half-felt.',
    body: 'Most of our overwhelm is from carrying a list of things we are not actually working on. Pick one. The other nine can wait. They are not as urgent as they feel.',
    action: 'Name the one thing you will move forward today. Put the rest on a parking lot.',
    theme: 'Discipline',
    order: 1,
    is_pro: false,
  },
  {
    slug: 'the-half-second',
    title: 'The half-second',
    hook: 'Between the heat and the response, there is a half-second. The whole practice is that half-second.',
    body: 'In that gap, the reactive brain loses 80% of its force. What remains is information, not impulse. The version of you that acts in the half-second is the version of you that other people remember.',
    action: 'The next time the heat rises, count to three. Notice what you say instead of what you were about to say.',
    theme: 'Mindfulness',
    order: 2,
    is_pro: false,
  },
  {
    slug: 'the-citadel',
    title: 'The citadel',
    hook: 'You have a place inside you that no one can enter unless you let them.',
    body: 'Marcus Aurelius had a small, locked room he called the citadel. It was the place he was still himself — even when the senators were flattering him, even when the generals needed him. The citadel is not a place. It is a practice. Before you respond to anything, take a half-second and ask: where is this coming from?',
    action: 'Pick one message you are about to send. Wait an hour. Re-read. Notice the answer is usually obvious by then.',
    theme: 'Perspective',
    order: 3,
    is_pro: true,
  },
  {
    slug: 'name-it-to-tame-it',
    title: 'Name it to tame it',
    hook: 'What we name, we can hold. What we cannot name, holds us.',
    body: 'When the feeling rises — fear, anger, shame, envy — name it. Out loud, if you can. "I am feeling anxious." "I am feeling envious." The act of naming moves the feeling from the reactive brain to the observing brain. The observing brain does not panic.',
    action: 'Next time a feeling spikes, name it. One word. Say it out loud. Notice what changes in 30 seconds.',
    theme: 'Mindfulness',
    order: 4,
    is_pro: false,
  },
  {
    slug: 'the-page',
    title: 'The page',
    hook: 'Two minutes in the morning. Two minutes at night. That is the practice.',
    body: 'Marcus wrote the twelve books of Meditations in his tent, by lamplight, late at night. He was not writing for an audience. He was writing for himself. The journal is a place to do four things you cannot reliably do in your head: catch your impressions, audit your day, talk to yourself, hold yourself to a standard.',
    action: 'Tomorrow morning, write three sentences before you check your phone. Tonight, write three sentences before you sleep. That is the practice.',
    theme: 'Discipline',
    order: 5,
    is_pro: true,
  },
  {
    slug: 'the-cold-shower',
    title: 'The cold shower',
    hook: 'You can prepare for the unchosen discomforts of life the way an athlete prepares for a race: in training, not at the event.',
    body: 'A cold shower is a small, chosen version of a large, unchosen version. The skipped meal. The hard year. The unchosen discomfort will arrive — the question is whether you have met it before. The trained version of you recognizes it. "I have been here. I can do this."',
    action: 'Pick one hardship this week. A cold shower. A walk in the rain. A skipped meal. Notice that nothing broke. Notice the rest of the day has a quieter quality.',
    theme: 'Discipline',
    order: 6,
    is_pro: false,
  },
  {
    slug: 'the-room',
    title: 'The room',
    hook: 'Events are not good or bad in themselves. It is the judgment we add that makes them so.',
    body: 'A delayed flight is an event. So is a rude reply, a missed promotion, a friend\'s bad decision. The flight, the reply, the promotion, the decision — these are inputs. They are not good or bad. What we do with them is the only thing that has a moral quality at all.',
    action: 'When something bothers you today, finish this: "The thing I am upset about is — and the part of it that is in my control is —." If you can\'t fill in the second half, you have found your suffering.',
    theme: 'Perspective',
    order: 7,
    is_pro: true,
  },
];
